pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["abbrev_brute.htm","Skróć do gwarancji","Skróć do gwarancji LC English Deutsch Español Français Italiano Rусский To pole wyboru \"gwarancji\" trafienia określonego poziomu trafień dla Twoic...",""],
["about.htm","O Programie","O p r o g r a m i e .... LC English Deutsch Español Français Italiano Rусский Lotto CAD w skrócie zwany przez użytkowników w skrócie LC to program...",""],
["again_and_check.htm","Powtórz i sprawdz z polem edycji","Powtórz i sprawdź z polem edycji LC English Deutsch Español Français Italiano Rусский Opcja powoduje powtórzenie kombinacji z opcjami ostatnio wyb...",""],
["again_and_check_history.htm","Powtórz i sprawdz w historii losowań","Powtórz i sprawdź w historii losowań LC English Deutsch Español Français Italiano Rусский Opcja powoduje powtórzenie kombinacji z opcjami ostatnio...",""],
["another_upload_methods.htm","Inne metody uzupelniania bazy losowań","Inne metody uzupelniania bazy losowań LC English Deutsch Español Français Italiano Rусский Istnieje kilka sposobów wprowadzania danych jeżeli nie ...",""],
["a_read_whell_on_day.htm","A opcja wczytaj losowanie z dnia","Powoduje wczytanie losowania z wybranego z rozwijalnego kalendarza dnia losowania. Uwaga : kliknięcie na nazwę miesiąca powoduje rozwinięcie pola ...",""],
["a_sidebarfloatselectgame.htm","Przyciski Wyboru Gier","Są to pływające przyciski wyboru bieżącej gry. Wybór gry przełącza bazę danych na wybraną grę i resetuje wszystkie ustawienia i zmienne na takie j...",""],
["check_in_history.htm","W historii losowań","Sprawdź w historii losowań LC English Deutsch Español Français Italiano Rусский zakłady wpisane w polu tekstowym \"losowania\" można sprawdzić z los...",""],
["check_tickets.htm","Z polem edycji","Sprawdź z polem edycji LC English Deutsch Español Français Italiano Rусский sprawdzanie z polem edycji odbywa się w czasie rzeczywistym ( tzn. w c...",""],
["combine_function.htm","Rodzaje funkcji losujących (kombinacji)","Rodzaje funkcji losujących (kombinacji) LC English Deutsch Español Français Italiano Rусский Program oferuje kilkanaście rodzai i pod rodzaj kombi...",""],
["combine_num_combine.htm","Kombinacja na jej numer","Kombinacja na jej numer LC English Deutsch Español Français Italiano Rусский Jak powszechnie wiadomo, wszystkich kombinacji liczb w typowej grze l...",""],
["comb_all.htm","Kombinacja wszystkich XX liczb","KOMBINACJA WSZYSTKICH XX LICZB LC English Deutsch Español Français Italiano Rусский ",""],
["comb_another.htm","Inne kombinacje","Inne kombinacje LC English Deutsch Español Français Italiano Rусский Są to kombinacje dostępne z menu głównego : Kombinacja pełna z liczb umieszcz...",""],
["comb_equal.htm","Kombinacja Równomierna","Kombinacja równomierna LC English Deutsch Español Français Italiano Rусский Wybrany zestaw liczb jest roztasowany pomiędzy zadaną liczbę zakładów ...",""],
["comb_expotential.htm","Kombinacja Wykładnicza","KOMBINACJA WYKŁADNICZA LC English Deutsch Español Français Italiano Rусский Wybrany zestaw liczb jest roztasowany pomiędzy zadaną liczbę zakładów ...",""],
["comb_expotential_xx.htm","Kombinacja Wykładnicza XX","KOMBINACJA WYKŁADNICZA XX LC English Deutsch Español Français Italiano Rусский Zestaw wszystkich XX liczb gry jest roztasowany pomiędzy zadaną lic...",""],
["comb_gauss.htm","Kombinacje Gaussa","Kombinacje z dystrybucją Gaussa LC English Deutsch Español Français Italiano Rусский Krzywa rozkładu normalnego Gaussa ma charakterystyczny kształ...",""],
["comb_line.htm","Kombinacja Liniowa","KOMBINACJA LINIOWA LC English Deutsch Español Français Italiano Rусский Wybrany zestaw liczb jest roztasowany pomiędzy zadaną liczbę zakładów w ta...",""],
["comb_line_xx.htm","Kombinacja Liniowa XX","KOMBINACJA LINIOWA XX LC English Deutsch Español Français Italiano Rусский Zestaw wszystkich XX liczb gry jest roztasowany pomiędzy zadaną liczbę ...",""],
["comb_quick_pick.htm","Kombinacja ChybiłTrafił XX","KOMBINACJA \"CHYBIŁ-TRAFIŁ\" XX LC English Deutsch Español Français Italiano Rусский Zestaw wszystkich XX liczb gry jest roztasowany pomiędzy zadaną...",""],
["comb_random.htm","Kombinacja Przypadkowa","KOMBINACJA PRZYPADKOWA LC English Deutsch Español Français Italiano Rусский Wybrany zestaw liczb jest roztasowany pomiędzy zadaną liczbę zakładów ...",""],
["comb_swap.htm","Kombinacje przemienne","Kombinacje przemienne LC English Deutsch Español Français Italiano Rусский Są to kombinacje analogiczne do kombinacji wykładniczej z wybranej pacz...",""],
["comb_systems.htm","Kombinacje systemowe","KOMBINACJE SYSTEMOWE LC English Deutsch Español Français Italiano Rусский Kombinacje te polegają na tym, że do roztasowania wybranej przez Ciebie ...",""],
["config_what_make.htm","Jak to zrobic","Jak skonfigurować nową grę LC ",""],
["contents.htm","Wprowadzenie","LottoCAD 2012 by (c) Wojar Software LC English Deutsch Español Français Italiano Rусский Gratulujemy wyboru, doskonałego albo prawie doskonałego p...",""],
["cover_bat.htm","Cover BAT","Program pomocniczy CoverBAT LC English Deutsch Español Français Italiano Rусский Jest to unikalny w świecie program pomocniczy do produkcji system...",""],
["edytorphp.htm","Edytor PHP","Edytor PHP LC English Deutsch Español Français Italiano Rусский Po wybraniu z menu Narzędzia opcji PHP wyświetlony zostanie formularz Edytora PHP....",""],
["filter_przyklad.htm","Przyklad filtracji","Przyklad filtracji MHD LC English Deutsch Español Français Italiano Rусский Na poniższym przykładzie pokażę jak w pełni wykorzystać filtry MHD i f...",""],
["filtravg.htm","FiltrAVG","Filtr AVG (średniej w kolumnie) LC English Deutsch Español Français Italiano Rусский Jeżeli obliczymy dla wszystkich losowań w historii, odchyleni...",""],
["filtrhd.htm","FiltrFHD","FHD filtr liczb twardych wybieranych LC English Deutsch Español Français Italiano Rусский Zadaniem filtra jest sprawdzić czy w generowanych zakład...",""],
["filtrmhd.htm","FiltrMHD","MHD wielokrotny filtr liczb twardych wybieranych LC English Deutsch Español Français Italiano Rусский Działanie filtra jest analogiczne do działan...",""],
["filtrspacji.htm","Filtr spacji","Filtr spacji LC English Deutsch Español Français Italiano Rусский Spacja w słownictwie komputerowym znaczy dosłownie odstęp. Analizą odstępów kole...",""],
["filtrzakresow.htm","Filtr zakresow","Filtr zakresow LC English Deutsch Español Français Italiano Rусский Filtr zakresów filtruje generowane zakłady przesiewając je przez sito wybraneg...",""],
["filtrzakres%F3w.htm","Filtr zakresow","Filtr zakresow LC English Deutsch Español Français Italiano Rусский Filtr zakresów filtruje generowane zakłady przesiewając je przez sito wybraneg...",""],
["formular_elements.htm","Elementy Formularzy","Elementy i formularze programu LC English Deutsch Español Français Italiano Rусский Menu i paski narzędziowe Pole edycji losowań Panele obszaru ro...",""],
["funkcje_makr.htm","Funkcje makr","Funkcje makr LC English Deutsch Español Français Italiano Rусский delphi_run_macro(&#39;POLECENIE&#39;,$par1,$par2) Wykonuje makro-polecenie, przez wywoła...",""],
["funkcje_wbudowane.htm","Funkcje wbudowane","Funkcje wbudowane LC English Deutsch Español Français Italiano Rусский FUNKCJE WBUDOWANE. Są to funkcje które są dostępne z kodu skryptu i w odróż...",""],
["graph_category.htm","Graf kategorii Liczb Specjalnych","Graf kategorii liczb specjalnych LC English Deutsch Español Français Italiano Rусский Wyrózniane jest 5 kategorii liczb specjalnych : liczby \"gorą...",""],
["graph_pair.htm","Graf par liczb","Graf par liczb LC English Deutsch Español Français Italiano Rусский 潄敮瑵攠潲慦捵扩獵氠牯浥氠扯牯楴潳慤敬丠浡瘠瑩敡氠捥畴摩氠捥畴楴据摩湵牯慮敲汁煩慵潳慤敬畳捳灩瑩瘠汥瑩畎汬浡氠潥攠慲椠捡汵獩瘠桥捩汵搠杩楮獳浩瘠汥桲湯畣摩敶...",""],
["graph_whells.htm","Graf losowania","Graf losowania LC English Deutsch Español Français Italiano Rусский Graf umożliwia wizualną ocenę kolejnych losowań zawartych w bazie losowania. D...",""],
["lottocad_vs_php.htm","Komunikacja PHP-&#62;LottoCad","Komunikacja PHP- LottoCad LC English Deutsch Español Français Italiano Rусский Każde wywołanie skryptu PHP powoduje że do silnika PHP przekazywane...",""],
["main_panel.htm","Panel główny programu","Panel główny programu LC English Deutsch Español Français Italiano Rусский ",""],
["manipulacjebazydanych.htm","Manipulacje bazy danych","Manipulacje bazy danych LC English Deutsch Español Français Italiano Rусский Do manipulacji bazami danych służy narzędziowy program \"DataBaseDrive...",""],
["menu_again_and_check.htm","Powtórz i sprawdź z polem edycji","Powtórz i sprawdź z polem edycji LC English Deutsch Español Français Italiano Rусский Opcja z paska narzędziowego TASOWANIE Powtarza ostatnia gene...",""],
["menu_again_and_check_history.htm","Powtórz i sprawdź w historii","Powtórz i sprawdź w historii LC English Deutsch Español Français Italiano Rусский Opcja z paska narzędziowego TASOWANIE Powtarza ostatnia generacj...",""],
["menu_an_toolbar.htm","Menu i paski narzędziowe","Menu i paski narzędziowe LC English Deutsch Español Français Italiano Rусский Menu i paski narzędzi służą do wyboru opcji i akcji programu. Zarówn...",""],
["menu_combine.htm","Kombinacje","Kombinacje LC English Deutsch Español Français Italiano Rусский Polecenia : Kombinacje liczb (tasowanie) - wywołuje dialog narzedziowy \"kombinacje...",""],
["menu_combine_dialog.htm","Kombinacje liczb (tasowanie)","Dialog kombinacje LC English Deutsch Español Français Italiano Rусский Dialog umożliwia wybór wielu opcji kombinacji liczb i sposobów wyboru paczk...",""],
["menu_combine_select_number.htm","Wybór liczb do kombinacji","Wybór liczb do kombinacji LC English Deutsch Español Français Italiano Rусский Porcje liczb można wybrać : łatwe wprowadzanie ciągów liczb np. 10....",""],
["menu_edit.htm","Edycja","Edycja LC English Deutsch Español Français Italiano Rусский Zawiera : Standardowe opcje obsługi edytora tekstowego, opcję sortuj, opcję \"usuń lini...",""],
["menu_file.htm","Plik","Menu Pliki LC English Deutsch Español Français Italiano Rусский --------------------------------------------------- Otwórz z ... Zapisz do ... Zap...",""],
["menu_file_game_manager.htm","Menadżer gier liczbowych","Manager gier LC English Deutsch Español Français Italiano Rусский Wybranie tej opcji wywołuje dialog obsługi baz danych które przechowują informac...",""],
["menu_file_load_save_to_base.htm","Zapisz do ... bazy zakładów","Zapis i odczyt zakładów z bazy danych LC English Deutsch Español Français Italiano Rусский Z (do) panela tekstowego można zapisać (odczytać) do (z...",""],
["menu_file_load_save_to_file.htm","Otwórz z ... pliku tekstowego","Zapis i odczyt zakładów z plików LC English Deutsch Español Français Italiano Rусский Zakłady z paneli tekstowych zapisywane są na dysku w postaci...",""],
["menu_file_print.htm","Drukuj, podgląd wydruku","Drukowanie kuponów gry LC English Deutsch Español Français Italiano Rусский Opcja umożliwia wydrukowanie kuponów bieżącej gry na kuponach oryginal...",""],
["menu_filters.htm","Filtry","Filtry LC English Deutsch Español Français Italiano Rусский Opcje zgrupowane w menu Filtry służą do obsługi filtracji generowanych zakładów. ",""],
["menu_filters_descr.htm","Filtry opis","Filtry opis LC English Deutsch Español Français Italiano Rусский Z pomocą filtrów można odfiltrować zakłady które mają niewielką szansę dać wygran...",""],
["menu_filters_diff.htm","Filtr róznicy","Filtr róznicy LC English Deutsch Español Français Italiano Rусский Filtr działa analogicznie jak filtr sumy z tym że dotyczy maksymalnej róznicy (...",""],
["menu_filters_hits.htm","Filtr Trafień","Filtr trafień w historii losowań LC English Deutsch Español Français Italiano Rусский Jak wynika z obserwacji z realnej gry z ponad 600 losowań po...",""],
["menu_filters_parity.htm","Parzystości","Filtr nieparzyste/parzyste LC English Deutsch Español Français Italiano Rусский W filtrze parzystości dostępnych jest dla gry Lotto (6/49), siedem...",""],
["menu_filters_string.htm","Szeregu kolejnych liczb","Filtr szeregu kolejnych liczb LC English Deutsch Español Français Italiano Rусский Wykres filtra szeregu kolejnych liczb pokazuje jak w losowaniac...",""],
["menu_filters_sum.htm","Sumy","Filtr sumy LC English Deutsch Español Français Italiano Rусский Działanie filtra najlepiej wyjaśni przykładowa ilustracja z programu : W realnej g...",""],
["menu_filters_what_use.htm","Przyklad filtracji SPS","Przykład filtracji SPS LC English Deutsch Español Français Italiano Rусский 1. Wywołujemy bardzo skuteczny graf losowań (tzw. dywan wyników) i z p...",""],
["menu_full_syst_filtered.htm","Odfiltrowany system pełny","Odfiltrowany system pełny LC English Deutsch Español Français Italiano Rусский Opcja : Odfiltrowany system pełny z liczb pola edycji. Wykonuje sys...",""],
["menu_help.htm","Pomoc","Pomoc LC English Deutsch Español Français Italiano Rусский ",""],
["menu_main.htm","Menu główne","Menu główne LC English Deutsch Español Français Italiano Rусский Menu rozwijalne : Pasek menu zawiera rozwijalne opcje wspólne dla wszystkich rodz...",""],
["menu_report.htm","Raporty","Menu grupuje opcje raportów i zestawień wyświetlanych w osobnych tabelach lub w paneach tekstowym w postaci tabel tekstowych. ",""],
["menu_report_stow.htm","Raport liczb stowarzyszonych-z poprzednim losowaniem","Raport liczb stowarzyszonych-z poprzednim losowaniem LC English Deutsch Español Français Italiano Rусский Liczby stowarzyszone to takie liczby któ...",""],
["menu_report_tabskut.htm","Tabela skutecznosci typowania kategorii liczb specjalnych","Tabela skuteczności typowania kategorii liczb specjalnych LC English Deutsch Español Français Italiano Rусский Raport wyświetlany jest w postaci t...",""],
["menu_report_trafedit.htm","Raport trafien we wszystkich losowaniach","Raport trafień we wszystkich losowaniach LC English Deutsch Español Français Italiano Rусский Raport w postaci tekstowej wyświetla tabelę w której...",""],
["menu_report_traf_los.htm","Raport trafień liczb z głównego pola edycji","Raport trafień liczb z głównego pola edycji LC English Deutsch Español Français Italiano Rусский ",""],
["menu_report_whells.htm","Raport o filtach losowan","Raport o filtach losowań LC English Deutsch Español Français Italiano Rусский Raport ten wyświetla informacje o ustawieniach filtrów z kombinacji ...",""],
["menu_skrypty_php.htm","Skrypty PHP","Skrypty PHP LC English Deutsch Español Français Italiano Rусский . Polecenia Skrypty PHP - Edytor - Uruchamia edytor skryptów PHP. - Rozwija podme...",""],
["menu_stats.htm","Menu Statystyki","Menu Statystyki LC English Deutsch Español Français Italiano Rусский ",""],
["menu_tool.htm","Narzędzia","Narzędzia LC English Deutsch Español Français Italiano Rусский Opcja menu grupuje polecenia dodatkowych narzędzi programu. ",""],
["menu_tool_calculators.htm","Kalkulatory","Kalkulatory LC English Deutsch Español Français Italiano Rусский Z menu narzędzia wywołać można kalkulatory : 1. Prosty kalkulator arytmetyczny 2....",""],
["menu_tool_coverbat.htm","Przewodnik (wizard) po systemach skróconych.","Przewodnik (wizard) po systemach skróconych. LC English Deutsch Español Français Italiano Rусский Wielu użytkowników ma trudności w posługiwaniu s...",""],
["menu_tool_fast_combine.htm","Szybki pasek kombinacji","Jest to pasek narzędziowy- kalendarz dla formularza kombinacje. Jeżeli formularz kombinacje jest aktywny otworzony) z pomocą paska można zmieniać ...",""],
["menu_tool_organiser.htm","Pamietnik organizer","Pamiętnik (organizer) LC English Deutsch Español Français Italiano Rусский ",""],
["menu_tool_update.htm","Uzupelnianie Bazy","Uzupełnianie bazy losowań LC English Deutsch Español Français Italiano Rусский Opcję wybiera się z menu Narzędzia. Umożliwia zaktualizowanie losow...",""],
["mligapozycji.htm","Liga pozycji","Liga pozycji LC English Deutsch Español Français Italiano Rусский ",""],
["mmapaodstepow.htm","Mapa odstepow","Mapa odstępów LC English Deutsch Español Français Italiano Rусский Jest to tabela umozliwiająca obserwację i manipulowanie kolumnami z informacją ...",""],
["mraportkombinacji.htm","Raport kombinacji","Raport Kombinacji LC English Deutsch Español Français Italiano Rусский Dla każdego losowania z ustawionego zakresu dat analizy, raport ten sprawdz...",""],
["mraportlosowan.htm","Raport Losowan","Raport losowań LC English Deutsch Español Français Italiano Rусский Raport wyświetla statystyki trafień losowań i ułatwia wybór losowania ( losowa...",""],
["mraportpozycji.htm","Raport pozycji","Raport pozycji LC English Deutsch Español Français Italiano Rусский Wybrane na podstawie raportów losowań i kombinacji określone pozycje można wpi...",""],
["mraportskutecznosci.htm","Raport skutecznosci","Raport skuteczności LC English Deutsch Español Français Italiano Rусский ",""],
["opcjephp.htm","Opcje PHP","Opcje PHP LC English Deutsch Español Français Italiano Rусский W menu głównym programu opcja \"Skrypty PHP\" zawiera rozwijalne podmenu \"PHP Opcje \"...",""],
["options_limits.htm","Limity generacji zakładow","Limity generacji zakładów LC English Deutsch Español Français Italiano Rусский Jest to sub menu grupujące opcje limitów nieudanych generacji dla g...",""],
["option_spec_category.htm","Opcje dla kategorii liczb specjalnych","Opcje kategorii liczb specjalnych LC English Deutsch Español Français Italiano Rусский Opcje służą do ustawienia parametrów kategorii liczb specja...",""],
["panelprognozy.htm","Panel Prognozy","Panel Prognozy LC English Deutsch Español Français Italiano Rусский Pola edycji tego panelu służą do zadawania parametrów prognoz: Pole edycji \"Pr...",""],
["panel_league.htm","Liga liczb","Formularz liga liczb LC English Deutsch Español Français Italiano Rусский Formularz rankingu liczb wg ilości wystąpień w kolejnych losowaniach. El...",""],
["panel_league_descr.htm","LIGA LICZB","Liga liczb opis LC English Deutsch Español Français Italiano Rусский Opcje formularza dostępne są z menu kontekstowego wybieranego prawym przycisk...",""],
["panel_maps.htm","Mapa liczb","Mapa liczb czyli kolorowy zawrót głowy LC English Deutsch Español Français Italiano Rусский Mapa liczb jest tabelą w której liczby wylosowane ozna...",""],
["panel_tend.htm","Tendencje","Formularz tendencje LC English Deutsch Español Français Italiano Rусский Elementy formularza ",""],
["panel_tend_descr.htm","TENDENCJE","Formularz tendencje opis LC English Deutsch Español Français Italiano Rусский Tabela Panel zawiera pogrupowaną wg częstości w zadanym okresie loso...",""],
["panel_text.htm","Panele tekstowe","Tekstowe pola edycji LC English Deutsch Español Français Italiano Rусский Panel główny zawiera dwa pola edytorów tekstowych (a właściwie trzy): po...",""],
["panel_text_popmenu.htm","Menu kontekstowe pola zaklady","Menu kontekstowe edytora \"zakłady\" LC English Deutsch Español Français Italiano Rусский Edytor zakładów jest normalnym edytorem tekstowym z zaimpl...",""],
["panel_ticketbase.htm","Baza zawartych zakładów","Formularz bazy zawartych zakładów LC English Deutsch Español Français Italiano Rусский Formularz bazy zawartych zakładów. Elementy formularza ",""],
["panel_ticketbase_descr.htm","BAZA ZAKŁADÓW","baza zakładów opis LC English Deutsch Español Français Italiano Rусский Panel Baza zakładów zawiera tabelę Bazy Danych Zakłady. Kolumny tabeli W s...",""],
["panel_ticket_mode.htm","Losowania inaczej","Formularz Losowania inaczej LC English Deutsch Español Français Italiano Rусский Elementy formularza ",""],
["panel_ticket_mode_descr.htm","Losowania inaczej opis","Losowania inaczej opis LC English Deutsch Español Français Italiano Rусский Panel zawiera tabelę losowań rozłożonych w takiej formie w jakiej wyst...",""],
["panel_wheels.htm","Tabela losowan","Tabela losowan LC English Deutsch Español Français Italiano Rусский Jest tabelą bazy danych losowań bieżącej gry posortowaną wg. numerów losowań i...",""],
["panel_wheels_highlight.htm","zaznaczanie liczb","Zaznaczanie liczb w tabeli losowań LC English Deutsch Español Français Italiano Rусский Opcje z paska narzędziowego \"zaznaczanie liczb\" powodują z...",""],
["panel_wheels_selection.htm","wybieranie liczb","Wybieranie liczb z tabeli losowań LC English Deutsch Español Français Italiano Rусский Z tabeli losowań można wybierać liczby do pola edycji lub s...",""],
["php.htm","PHP","Język skryptowy PHP LC English Deutsch Español Français Italiano Rусский Program LottoCad wyposażony został w język skryptowy. Język ten podobnie ...",""],
["php_opcje.htm","Serwer HTTP","Serwer HTTP LC English Deutsch Español Français Italiano Rусский Serwer HTTP jest usługą z którą program porozumiewa się z pomocą protokołu siecio...",""],
["predictionsreport.htm","Raport Prognozy","Raport Prognozy LC English Deutsch Español Français Italiano Rусский Nie ma i przypuszczam ze długo nie będzie metod matematycznych, złotych srodk...",""],
["prognozyopcje.htm","Panel Opcje","W polu tekstowym \"Raport dla [ ] losowań\" ustawia się ilość losowań wstecz branych pod uwagę przy wykonywanych analizach skuteczności prognoz. Jeż...",""],
["prognozyopis.htm","Prognozy opis","Prognozy opis LC English Deutsch Español Français Italiano Rусский Prognozy najprościej mówiąc mają zadanie wyłowić liczby których występowanie w ...",""],
["prognozy_game_trick.htm","Prognozy przyklady gry","Prognozy przykłady gry LC English Deutsch Español Français Italiano Rусский Praktyczne przykłady gry: Wykonujemy prognozy ZG-?Z od 1 do 15 cykli, ...",""],
["progn_what_select.htm","jak wybierać prognozy ","Jak wybierać prognozy LC English Deutsch Español Français Italiano Rусский Obserwacja statystyk może znakomicie ułatwić podjęcie decyzji wyboru me...",""],
["programs_tool.htm","Programy pomocnicze","PROGRAMY POMOCNICZE LC English Deutsch Español Français Italiano Rусский Producent systemów Producent Systemów.exe Unikalny i niespotykany w innyc...",""],
["program_configure_method.htm","Konfigurowanie programu","Konfigurowanie programu LC English Deutsch Español Français Italiano Rусский Program Lotto CAD jest uniwersalnym programem obsługującym wiele gier...",""],
["prog_sys_check_system.htm","Sprawdzanie systemu","Sprawdzanie systemu LC English Deutsch Español Français Italiano Rусский opcje z menu sprawdź, umożliwiają sprawdzenie kombinacji : właśnie wyprod...",""],
["prog_sys_load_f_dbase.htm","Odczytanie systemu z bazy","Odczytanie systemu z bazy LC English Deutsch Español Français Italiano Rусский System można odczytać ( np. w celu sprawdzenia lub zapisu do pliku ...",""],
["prog_sys_load_f_file.htm","Odczytanie systemu z pliku","Odczytanie systemu z pliku LC English Deutsch Español Français Italiano Rусский Patrz zapis odczyt do i z pliku ",""],
["prog_sys_new_system.htm","Nowe systemy","Nowe systemy LC English Deutsch Español Français Italiano Rусский W polach edycji mieszczących się w nagłówku ustawia się parametry wejściowe syst...",""],
["prog_sys_pro.htm","Producent systemów","Producent systemów LC English Deutsch Español Français Italiano Rусский Panel główny programu : ",""],
["prog_sys_save_to_dbase.htm","Zapisywanie systemu do bazy","Zapisywanie systemu do bazy LC English Deutsch Español Français Italiano Rусский Po sprawdzeniu systemu wyprodukowanego lub odczytanego z pliku mo...",""],
["prog_sys_save_to_file.htm","Zapisywanie systemu do pliku","Zapisywanie systemu do pliku LC English Deutsch Español Français Italiano Rусский System można odczytać i zapisać z i do pliku w formacie tekstowy...",""],
["prog_sys_shedule.htm","Zadanie do wykonania","Zadanie do wykonania LC English Deutsch Español Français Italiano Rусский Wykonanie systemów można zautomatyzować wstawiając żądania wykonania sys...",""],
["quick_bar.htm","Szybki pasek wyboru","Boczny pasek programu LC English Deutsch Español Français Italiano Rусский Boczny pasek szybkiego wyboru służy do szybkiego przejścia do kolejnych...",""],
["raportliczbstowarzyszonych.htm","Raport liczb stowarzyszonych","Raport liczb stowarzyszonych LC English Deutsch Español Français Italiano Rусский Liczby stowarzyszone w tym samym losowaniu to liczby występujące...",""],
["raportmapyliczb.htm","Raport mapy liczb","Raport mapy liczb LC English Deutsch Español Français Italiano Rусский Raport ten służy do analizy skuteczności typowania na określone kolumny pos...",""],
["raportpewn.htm","Raport pewniakow","Raport pewniaków LC English Deutsch Español Français Italiano Rусский Raport ten powstał na życzenie użytkownika i wynika on z jego doświadczeń w ...",""],
["raportpozycji.htm","Raport pozycji","Raport pozycji LC English Deutsch Español Français Italiano Rусский Panel sterowania roportami pozycji. Raporty pozycji służą do wyświetlania stat...",""],
["raport_trafien_trendow_liczb.htm","Raport trafien trendow liczb","Raport trafień trendów liczb LC English Deutsch Español Français Italiano Rусский Nowy raport trafień dla wyliczanych trendów liczb pomaga wytypow...",""],
["report_tickets_combine.htm","Raport wartosci filtrow zakładow","Raport wartośći filtrów zakładów LC English Deutsch Español Français Italiano Rусский ",""],
["spec_numb_algorythm.htm","Algorytm podziału liczb gry na kategorie specjalne.","Algorytm podziału liczb gry na kategorie specjalne. LC English Deutsch Español Français Italiano Rусский Jest to specjalny sposób podziału wszystk...",""],
["statistics.htm","Statystyki wystepowania liczb","Statystyki występowania liczb LC English Deutsch Español Français Italiano Rусский Do wyboru opcji służy pasek narzędzi \"statystyki\" lub odpowiedn...",""],
["systemystrefowekrokpokroku.htm","Systemy strefowe","Ciekawe układy można osiągnąć grając systemami strefowymi po trzy liczby w każdej strefie z wybieraniem do zakładów po dwie liczby w strefie. To ł...",""],
["sztuczkiikruczki.htm","Sztuczki i kruczki","Sztuczki i kruczki LC English Deutsch Español Français Italiano Rусский Rozdział zawiera kilka ważnych wskazówek dla użytkowników programu. ",""],
["text_option.htm","Opcje pola tekstowego","Opcje pól tekstowych Ustaw opcje paneli : Wywołuje pasek narzędziowy do ustawienia podstawowych opcji paneli tekstowych. Najczęściej w pasku tym u...",""],
["tipsmemo.htm","Pole tekstowe sposoby","Pole tekstowe sposoby LC English Deutsch Español Français Italiano Rусский Pole tekstowe jest normalnym edytorem tekstowym o sporych mozliwosciach...",""],
["toolbars.htm","Paski narzedziowe","Paski narzędziowe LC English Deutsch Español Français Italiano Rусский Paski narzędziowe służą do zgrupowania opcji w postaci pasków z narzędziami...",""],
["tool_combine.htm","kombinacje Liczb","Pasek kombinacji i sprawdzania zakładów LC English Deutsch Español Français Italiano Rусский Pasek narzędzi dialog narzędziowy Kombinacje . Umożli...",""],
["tool_main.htm","Pole edycji losowań","POLE EDYCJI LOSOWAŃ LC English Deutsch Español Français Italiano Rусский Umieszczone jest na pasku narzędziowym i służy do wprowadzania wyników lo...",""],
["zmienne_php.htm","Zmienne PHP","Zmienne PHP LC English Deutsch Español Français Italiano Rусский Zmienne Każda zmienna w PHP poprzedzona jest znakiem $(dolar). Zmienna to umowne ...",""]];
